### PR TITLE
Line length linter.

### PR DESCRIPTION
**Pull request by fernandalavalle**
This PR adds a linter to check line length within a module following these rules: 

        - Generally, lines should not exceed 80 characters.
        - It is always okay to exceed this limit if the line contains a URL.
        - Lines that are within a triple-quoted string may also exceed the limit
          if the triple-quoted string is not a docstring.
        - Only comments, docstrings, or lines containing a string are
            checked.

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/line-length-linter/1)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @fernandalavalle)

---

*[line_length_linter/lint.py, line 11 at r1](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFoQ5Ey5NN2B3KT2-Lr:-LFoQ5Ey5NN2B3KT2-Ls:b-43xvh0) ([raw file](https://github.com/mtlynch/line-length-linter/blob/5af20b1399298c8f181a50423626657dafbe7009/line_length_linter/lint.py#L11)):*
> ```Python
> # Matches URLs that start with http or https, like https://ketohub.io.
> _URL_PATTERN = re.compile(
>     r'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)'
> ```

This is interesting because it exceeds line length, but is okay. I guess we should refine the rule to say that raw strings (`r'whatever'`) are always okay.

But in addition:

* Can we add a step to the `build` script where we lint check `lint.py`? [this might help](https://wp.prepsmarter.com/wp-content/uploads/2017/12/deeper.jpg)
* Can we add a >80 character raw string to `test_file_for_lint.py`?

---

*[line_length_linter/lint.py, line 98 at r1](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFoREEcA38_X4dQ5Fjl:-LFoREEcA38_X4dQ5Fjm:b-rwp40r) ([raw file](https://github.com/mtlynch/line-length-linter/blob/5af20b1399298c8f181a50423626657dafbe7009/line_length_linter/lint.py#L98)):*
> ```Python
>                     # We add 1 to the line number because arrays are 0 indexed
>                     # but line numbers are not.
>                     self.add_message('C0001', node=node, line=line_number + 1)
> ```

I prefer not to nest the logic so deeply. Can we rewrite this as:

```python
if not _over_line_length(line):
  return
if _contains_url(line):
  return
if is_one_line_triple_quote(line)
  return
self.add_message(...)
```

Ditto for the `if` in `_check_docstring` but I care less strongly about that one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mtlynch/line-length-linter/1)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @mtlynch)

---

*[line_length_linter/lint.py, line 11 at r1](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFoQ5Ey5NN2B3KT2-Lr:-LFonFwr5KxC6zRZFhtG:b-7rl0jd) ([raw file](https://github.com/mtlynch/line-length-linter/blob/5af20b1399298c8f181a50423626657dafbe7009/line_length_linter/lint.py#L11)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

This is interesting because it exceeds line length, but is okay. I guess we should refine the rule to say that raw strings (`r'whatever'`) are always okay.

But in addition:

* Can we add a step to the `build` script where we lint check `lint.py`? [this might help](https://wp.prepsmarter.com/wp-content/uploads/2017/12/deeper.jpg)
* Can we add a >80 character raw string to `test_file_for_lint.py`?
</blockquote></details>

done.

---

*[line_length_linter/lint.py, line 98 at r1](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFoREEcA38_X4dQ5Fjl:-LFopVW0E2P-UL2f7SfL:b-7rl0jd) ([raw file](https://github.com/mtlynch/line-length-linter/blob/5af20b1399298c8f181a50423626657dafbe7009/line_length_linter/lint.py#L98)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I prefer not to nest the logic so deeply. Can we rewrite this as:

```python
if not _over_line_length(line):
  return
if _contains_url(line):
  return
if is_one_line_triple_quote(line)
  return
self.add_message(...)
```

Ditto for the `if` in `_check_docstring` but I care less strongly about that one.
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mtlynch/line-length-linter/1)*

**Comment by mtlynch** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @mtlynch and @fernandalavalle)

---

*[.pylintrc, line 4 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowNKwEyzrUXZ-YS5G:-LFowNKwEyzrUXZ-YS5H:b-mrye59) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/.pylintrc#L4)):*
> ```
> 
> # Load the DocStringChecker plugin.
> load-plugins=lint,line_length_lint
> ```

We need to update the comment to mention line_length_lint (ditto below)

---

*[build, line 23 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowWyVEqE8MZ93_ea2:-LFowWyVEqE8MZ93_ea3:bsj318e) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/build#L23)):*
> ```
> # Check docstrings for style consistency.
> PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker:$(pwd)/line_length_linter \
>   pylint --reports=n --rcfile=.pylintrc "$SOURCE_DIR" "$TEST_DIR"
> ```

`TEST_DIR` is undefined. We actually don't want to lint the `tests` dir because it intentionally contains linter errors.

---

*[line_length_linter/.pylintrc, line 3 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowiNp8dZY-IvAqsOX:-LFowiNp8dZY-IvAqsOY:b-4b4cci) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/line_length_linter/.pylintrc#L3)):*
> ```
> [MASTER]
> 
> # Load the DocStringChecker plugin.
> ```

DocStringChecker -> line_length_linter

---


*Comments from [Reviewable](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-:-LFowuuA6iAE6UNj2i9a:bnfp4nl)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @mtlynch)

---

*[.pylintrc, line 4 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowNKwEyzrUXZ-YS5G:-LFozhsk2b3kJkW435Nc:b-7rl0jd) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/.pylintrc#L4)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

We need to update the comment to mention line_length_lint (ditto below)
</blockquote></details>

done.

---

*[build, line 23 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowWyVEqE8MZ93_ea2:-LFozV8BCmYR0pHT3-f4:b-7rl0jd) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/build#L23)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

`TEST_DIR` is undefined. We actually don't want to lint the `tests` dir because it intentionally contains linter errors.
</blockquote></details>

done.

---

*[line_length_linter/.pylintrc, line 3 at r2](https://reviewable.io/reviews/mtlynch/line-length-linter/1#-LFowiNp8dZY-IvAqsOX:-LFozae13TxaGQ0P1ITB:b-7rl0jd) ([raw file](https://github.com/mtlynch/line-length-linter/blob/d6d9dfd1b7df794fcff8d652cb9a1bc10b48973c/line_length_linter/.pylintrc#L3)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

DocStringChecker -> line_length_linter
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mtlynch/line-length-linter/1)*

**Pull request merged**
